### PR TITLE
Fix call to isV2Running

### LINKED ISSUE #179: When your video is not available at an external URL, the error message on the Display is incorrect.
<b>How it works now</b>
1. Add a video to your Presentation that is not in Storage. Ensure that the video is NOT at that URL.
2. Notice that when it plays in a Presentation, the error message shows: "There was a problem retrieving the file from Rise Cache" which is not the correct message. It should say "The selected file does not exist or has been moved to the trash".

<b>How it should work:</b>
The correct error message should appear on the Display.

### PR DESCRIPTION
**Pull request by donnapep**
`isV2Running` takes a callback function as a parameter. The function call was missing this callback.

Also, if RC v2 was running, `statusCode` was 0, which would result in no error message showing on the Display. `statusCode` is now set regardless of which version of Rise Cache is running.

Fixes #179.

### CODE REVIEW

**Comment by donnapep** [comment]
@Rise-Vision/delivery Please review. Thx.

File: test/integration/js/file.js [hunk 1]
```diff
@@ -231,22 +231,40 @@ suite( "Storage Errors", function() {
...
 
-    storage.dispatchEvent( new CustomEvent( "rise-cache-error", {
-      "detail": {
-        "error": {
-          "message": "The request failed with status code: 500"
-        }
-      },
-      "bubbles": true
-    } ) );
+    if ( isV2Running ) {
```
Comment (settinghead) [inline test/integration/js/file.js]: Don't quite understand the logic here. Isn't isV2Running always false according to rest of the code in this file?

Comment (donnapep) [inline test/integration/js/file.js]: @settinghead This file is used both [here](https://github.com/Rise-Vision/widget-video/blob/master/test/integration/storage-v1/file.html) and [here](https://github.com/Rise-Vision/widget-video/blob/master/test/integration/storage-v2/file.html). In the second HTML file, `isV2Running` is set to `true`.

The test cases are re-used for both Rise Cache v1 and Rise Cache v2. They're pretty much identical and we didn't want to have to duplicate the test cases for each one.

Thx.

**Comment by settinghead** [comment]
:+1:

**Comment by stulees** [comment]
@donnapep 👍
